import './globals.css'
import 'react-toastify/dist/ReactToastify.css'
import 'react-loading-skeleton/dist/skeleton.css'
import 'swiper/css'
import type { Metadata } from 'next'
import React from 'react'
import { ToastContainer } from 'react-toastify'
import AppContextProvider from '../../configs/store/useAppContext'
import { cookies } from 'next/headers'
import { User } from '../../types/user.type'
import { TokenType } from '@/src/constants/token'
import userApis from '@/src/apiRequests/user.api'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const cookieStore = cookies()
  let user: User | null = null
  const accessToken = cookieStore.get(TokenType.ACCESS_TOKEN)?.value ?? ''
  if (accessToken) {
    const userResponse = await userApis.sGetUserProfile(accessToken)
    user = userResponse.data
  }

  return (
    <html lang='en'>
      <body>
        <div
          id='__next'
          style={{ overflowX: 'hidden' }}
        >
          <AppContextProvider initUser={user}>
            <ToastContainer className='text-xl' />
            {children}
          </AppContextProvider>
        </div>
      </body>
    </html>
  )
}
